### ISSUE TITLE
Can data packages be stored on a private conda repository instead of on Anaconda cloud?

### ISSUE THREAD

**Issue by zhangzhen** [gogetdata/ggd-recipes#173]
I want to use GDD to manage our data in an enterprise environment, but cannot share our data on Anaconda cloud. Does GGD work also on a private conda repository? What should I do to make it work?

Cheers,
Zhen

**Comment by mikecormier** [comment]
@zhangzhen, can you explain a bit more about what you are trying to do?

**Comment by mikecormier** [comment]
@zhangzhen, I am closing this issue because I haven't heard back from you. If you are interested in private data packages you can read about it on the GGD docs: https://gogetdata.github.io/private_recipes.html. Feel free to contact us if you have any other questions.

**Comment by zhangzhen** [comment]
I've read the private_recipes part of the GGD docs, but the private recipes are not what I want. I want the bzip file created by `ggd check-recipe` to upload our private channel located at http://172.16.x.x:5000/ggd-genomics. `ggd install -c http://172.16.x.x:5000/ggd-genomics` can pull the bzip file and install this data package into an environment.
