### ISSUE TITLE
gsort 404 for hg19.genome

### ISSUE THREAD

**Issue by drmjc** [gogetdata/ggd-recipes#19]
Hi Brent,
this is a cool initiative - I need to download something from UCSC, so I thought i'd give this a go & hopefully contrib some formulae over time.

I hit a stumbling block though:

    $ conda install -c ggd-alpha hg19-ga4gh-problem-regions=20151116
    ...
    Fetching packages ...
    ...
    Extracting packages ...
    ...
    Linking packages ...
    Archive:  GA4GH_problem_regions.zip
      inflating: README.md               
      inflating: bad_promoter.bed        
      inflating: gc15.bed                
      inflating: gc15to20.bed            
      inflating: gc20to25.bed            
      inflating: gc25to30.bed            
      inflating: gc65to70.bed            
      inflating: gc70to75.bed            
      inflating: gc75to80.bed            
      inflating: gc80to85.bed            
      inflating: gc85.bed                
      inflating: heng_um75-hs37d5.bed    
      inflating: low_complexity_51to200bp.bed  
      inflating: low_complexity_gt200bp.bed  
      inflating: low_complexity_lt51bp.bed  
      inflating: self_chain.bed          
    > gsort version 0.0.2
    2016/07/08 17:06:19 http error downloading https://raw.githubusercontent.com/gogetdata/ggd-recipes/dev/genomes/hg19/hg19.genome. status: 404 Not Found
    Error: Error: pre-link failed: ggd-alpha::hg19-ga4gh-problem-regions-20151116-1###########                                                              |  50%

Swapping dev -> master in the url would help.

cheers,
Mark

**Comment by brentp** [comment]
I restored the dev branch for now. The recipe looks like it's been updated to point to master in git, but the build isn't updated. I'll explore.

**Comment by drmjc** [comment]
Thanks brentp, thant's working nicely now
cheers,
Mark
