### ISSUE TITLE
checks to add on installed recipes

### ISSUE THREAD

**Issue by brentp** [gogetdata/ggd-recipes#2]
- [x] some recipes download a .zip or .tar.gz make sure to clean this up or at least issue a warning.
- [x] implement checking of gtf and gff in check-sort-order
- [x] fasta (.fa) should have a .fai
- [x] recipe must have an about/summary
- [ ] there should be 1 canonical whole-genome fasta file per genome build with a recipe name of $build-sequence/
- [x] make sure that any files went to $PREFIX/share/ggd/$species/$genome-build/ and nowhere else.
- [ ] files should have consistent number of columns
- [ ] location of recipe (e.g. recipes/Homo_sapiens/hg19/ should match the species and genome-build specified in the yaml.

**Comment by brentp** [comment]
could be that anything that's not part of a .gz, .gz.tbi pair must be listed in an extra section in the yaml?

**Comment by mikecormier** [comment]
Closing this issue. These issues have been resolved in the newer versions of ggd.
