### ISSUE TITLE
using ggd recipes to manage indices

### ISSUE THREAD

**Issue by matthdsm** [gogetdata/ggd-recipes#25]
Hi Brent,

We're looking to migrate the reference data from our galaxy environment to something managed by ggd recipes (GREAT initiative btw, I really hope this get the same traction as bioconda). Do you suppose it's viable to use GGD recipes to manage indices for different tools?

It would be nice if it would be possible to add the recipe for a fasta file as dependency.
For example, to generate bwa idices the recipe should depend on the fasta and the bwa executable and place everything in the right directory.

Thanks!
Matthias

**Comment by brentp** [comment]
Hi @matthdsm you're suggesting exactly the use-case I have in mind when I switched ggd to using conda: software with data dependencies and data with software dependencies. 

We have some work to go, but @jbelyeu made some good progress on ggd during his rotation and we plan to continue that this year.

**Comment by matthdsm** [comment]
Great to hear! I you need help creating recipes for stuff, I'm willing to invest some time into that. I guess a good starting point would be to have the most common data ready for the popular model organisms (Zebrafish, mouse, fruitfly and human)

**Comment by mikecormier** [comment]
@matthdsm, I wanted to reach out to let you know that we have made a major push towards officially releasing ggd. I have taken over the project and have done some major overhaul to ggd. At this point, we are finalizing a few small items, but ggd is up and running. We are currently working to add recipe to ggd and I was wondering if you would be willing to help create some?

**Comment by matthdsm** [comment]
Hi @mikecormier 

Great to hear you've made progress!
I'd be glad to add a few recipes here and there, schedule permitting.
Do you think you could compile a list of essential datasets and/modifications that you'd like to have before release?
If possible, you could open an checkbox issue where we can ref all relevant PR's and check off the ones that are finished.

Cheers
M

**Comment by arq5x** [comment]
Yes, an issue with a checkbox list of recipes would be a fantastic way to track things.

**Comment by mikecormier** [comment]
Hey @matthdsm,

I will work on putting a list together for required datasets. In the meantime, with the time you have could you work on adding recipes that curate the data from UCSC and Ensembl? We have a few recipes from UCSC and Ensembl but would like to add as many datasets from UCSC and Ensembl as possible. 

Also, if you have any recipes you would like to add or know would be used please feel free to add those as well. 

Here is a [google sheet](https://docs.google.com/spreadsheets/d/18l_RrT1_TVoWA3usdyZd_QocGKL3hvpigNagBBitmxI/edit?usp=sharing) the provides the list of active ggd recipes we have created so far. As you add recipes will you also add them to this list?

Thanks

**Comment by matthdsm** [comment]
Hi Mike,

You might find it worthwile to check out [bcbio](https://github.com/bcbio/bcbio-nextgen) and [cloudbiolinux](https://github.com/chapmanb/cloudbiolinux/tree/master/ggd-recipes). I don't know if you're familiar with these projects, but @chapmanb and several others have been working on maintaining recipes based on the ggd principle.

Perhaps you're able to amend the recipes found there as a good starting point.
Cheers
M

**Comment by mikecormier** [comment]
Hey @matthdsm, I am going to close this issue. Thanks for your suggestion. 

If you haven't seen it already, we have uploaded a preprint of GGD to biorxiv: https://www.biorxiv.org/content/10.1101/2020.09.10.291377v2

GGD docs are here: https://gogetdata.github.io/

Feel free to add any recipes to GGD.
