### ISSUE TITLE
Link error

### ISSUE THREAD

**Issue by henrikstranneheim** [gogetdata/ggd-recipes#27]
I have installed ggd-cli (v0.0.6), which seem to work fine and then I tried to install hg19-dbsnp using conda, but that produced a link error and some conda warnings, se below. Also the GATK bundle structure has changed and no longer has the GATK version in the url.

$ conda install -c ggd-alpha hg19-dbsnp
Fetching package metadata .............
Solving package specifications: ..........

Package plan for installation in environment /develop/modules/miniconda2:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    hg19-dbsnp-138             |                0           1 KB  ggd-alpha

The following NEW packages will be INSTALLED:

    hg19-dbsnp: 138-0 ggd-alpha

Proceed ([y]/n)? y

Fetching packages ...
hg19-dbsnp-138 100% |##########################################################################################################################################################################################################| Time: 0:00:00 434.62 kB/s
Extracting packages ...
[      COMPLETE      ]|#############################################################################################################################################################################################################################| 100%
Linking packages ...

Package ggd-alpha::hg19-dbsnp-138-0 uses a pre-link script. Pre-link scripts are potentially dangerous  discouraged.
This is because pre-link scripts have the ability to change the package contents in the
package cache, and therefore modify the underlying files for already-created conda
environments.  Future versions of conda may deprecate and ignore pre-link scripts.
--2017-01-11 08:15:43--  ftp://gsapubftp-anonymous:*password*@ftp.broadinstitute.org/bundle/2.8/hg19/dbsnp_138.hg19.vcf.gz
           => “-”
Resolving ftp.broadinstitute.org... 69.173.80.251
Connecting to ftp.broadinstitute.org|69.173.80.251|:21... connected.
Logging in as gsapubftp-anonymous ... Logged in!
==> SYST ... done.    ==> PWD ... done.
==> TYPE I ... done.  ==> CWD (1) /bundle/2.8/hg19 ...
No such directory “bundle/2.8/hg19”.

gzip: stdin: unexpected end of file

LinkError: Link error: Error: pre-link failed: ggd-alpha::hg19-dbsnp-138-0

**Comment by brentp** [comment]
Yes, that .vcf.gz must have moved. I'll have a look at updating the recipe this week.
thanks for reporting.
