### ISSUE TITLE
RADAR .bed file has wrong coordinates

### ISSUE THREAD

**Issue by sergiigladchuk** [gogetdata/ggd-recipes#28]
I am not 100% sure, but most probably the converted RADAD .bed file which is transformed from [this file](http://lilab.stanford.edu/GokulR/database/Human_AG_all_hg19_v2.txt), has shifted start and end coordinates. The original db file has only 1 position (e.g. chr1 10187) - so .bed start and end positions should be chr1 10186 10187 (not 10187 10188).
This can be confirmed based on version 1 of RADAR db: [initial db](http://lilab.stanford.edu/GokulR/database/Human_AG_all_hg19.txt) vs. [their .bed file](http://lilab.stanford.edu/GokulR/database/Human_AG_all_hg19.bed)

It seams that people are using this recipe for annotation, and current annotation would be wrong for SNV, since it is referencing to position next to actual mutation.

**Comment by mikecormier** [comment]
@sergiigladchuk, this has been fixed: https://github.com/gogetdata/ggd-recipes/pull/118
