### ISSUE TITLE
Caching recipes locally? Planned feature? 

### ISSUE THREAD

**Issue by apeltzer** [gogetdata/ggd-recipes#42]
Hi! 

one thing that we had in an internal discussion recently, is that it would be nice to have a way to cache recipes locally, e.g. in a cluster environment. Downloading e.g. recipes with > 10GB of files for a pipeline is taking a lot of time, so with the possibility to store recipes locally and (re-) use them, would be something we'd be very interested. 

I had a look at the #24  issue, but that seems to be not directly related to this and I couldn't find anything related in the issues/documentation either.

**Comment by mikecormier** [comment]
Hi @apeltzer,

You shouldn't need to download a recipe each time you run your pipeline. Once a recipe is installed it is stored within your conda environment. It would be best to download the recipe prior to running your pipeline, then add the downloaded recipes to your pipeline. 

You can use 'ggd list-files' to locate where your recipe is stored. For example, if you are using the GRCh37 reference genome you would download it prior to running your pipeline, then within your pipeline you would use `ggd list-files` to find the recipe. You might add this code to your pipeline:
`reference_fasta="$(ggd list-files 'grch37-reference-genome' -s 'Homo_sapiens' -g 'GRCh37' -p 'hs37d5.fa')"`
