### ISSUE TITLE
Danio rerio (zebrafish) gsort genome file

### ISSUE THREAD

**Issue by idaL** [gogetdata/ggd-recipes#57]
Hi! We are trying to create recipes for ftp://ftp.ensembl.org/pub/release-91/gtf/danio_rerio/Danio_rerio.GRCz10.91.gtf.gz and ftp://hgdownload.soe.ucsc.edu/goldenPath/danRer10/bigZips/danRer10.fa.gz

Can we have the associated genome files used with gsort for them?

**Comment by arq5x** [comment]
Fantastic!  One can get this from UCSC as well.   The first 2 columns of the chromInfo.txt.gz file give the chrom and length for use with gsort.

    curl -s ftp://hgdownload.soe.ucsc.edu/goldenPath/danRer10/database/chromInfo.txt.gz | zless | cut -f 1,2 | head
chr4	76625712
chr7	74082188
chr5	71715914
chr3	62385949
chr6	60272633
chr2	59543403
chr1	58871917
chr9	56892771
chr16	55381981
chr20	55370968

**Comment by idaL** [comment]
Thank you @arq5x ! Do you have it for the ensembl file as well?

**Comment by mikecormier** [comment]
See https://github.com/gogetdata/ggd-recipes/issues/58#issuecomment-496594312

**Comment by mikecormier** [comment]
https://github.com/gogetdata/ggd-recipes/issues/58#issuecomment-497042984
