### ISSUE TITLE
ggd make-recipe: error: argument -s/--species: invalid choice

### ISSUE THREAD

**Issue by idaL** [gogetdata/ggd-recipes#58]
Encountered error below when making a danio rerio (zebrafish) recipe:
ggd make-recipe: error: argument -s/--species: invalid choice: 'Danio_rerio' (choose from u'Canis_familiaris', u'Mus_musculus', u'Drosophila_melanogaster', u'Homo_sapiens')

How can we resolve this? Thank you! (:

**Comment by mikecormier** [comment]
@idaL,
which genome builds will you be using/creating recipes for? (For Danio rerio)

**Comment by idaL** [comment]
@mikecormier Thank you Michael! danRer10 and GRCz10

**Comment by mikecormier** [comment]
@idaL,

This is now fixed. **Danio_rerio** is now included in the species list. The **danRer10** and **GRCz10** genome builds are also included. 

Per your question in https://github.com/gogetdata/ggd-recipes/issues/57, a gnome file for each of the two genome builds has been created. You can now use these files when running `gsort`. 

`https://raw.githubusercontent.com/gogetdata/ggd-recipes/master/genomes/Danio_rerio/GRCz10/GRCz10.genome`

and 

`https://raw.githubusercontent.com/gogetdata/ggd-recipes/master/genomes/Danio_rerio/danRer10/danRer10.genome`

Additionally, I have created a ggd-recipe for the reference genome for each of the two genome builds: 

`https://github.com/gogetdata/ggd-recipes/tree/master/recipes/genomics/Danio_rerio/GRCz10/grcz10-reference-genome-ensembl-v1`

and 

`https://github.com/gogetdata/ggd-recipes/tree/master/recipes/genomics/Danio_rerio/danRer10/danrer10-reference-genome-ucsc-v1`

This should get you started. Please let us know if you have additional questions.

**Comment by idaL** [comment]
Thank you so much @mikecormier ! Can you also provide us with the gsort genome files for GRCz11 and danRer11?

**Comment by mikecormier** [comment]
danRer11: 
`https://raw.githubusercontent.com/gogetdata/ggd-recipes/master/genomes/Danio_rerio/danRer11/danRer11.genome`

GRCz11:
`https://raw.githubusercontent.com/gogetdata/ggd-recipes/master/genomes/Danio_rerio/GRCz11/GRCz11.genome`


I have also added a reference genome recipe for each. (These will be available in the ggd-genomics channel later this evening) 

`danrer11-reference-genome-ucsc-v1`

`grcz11-reference-genome-ensembl-v1`
