### ISSUE TITLE
conda install post-link script issue

### ISSUE THREAD

**Issue by idaL** [gogetdata/ggd-recipes#71]
I tried conda-install a ggd recipe in a non-base environment, and encountered the following issue. But the same command works if I install in the base environment. I understand that it is recommended to use ggd install instead of conda install, but having this issue fixed would be nice (:

Downloading and Extracting Packages
danrer10-reference-g | 6 KB      | ######################################################################################################################################################################## | 100% 
Preparing transaction: done
Verifying transaction: done
Executing transaction: | ERROR conda.core.link:_execute_post_link_actions(720): An error occurred while installing package 'ggd-genomics::danrer10-reference-genome-ucsc-v1-1-1'.
LinkError: post-link script failed for package ggd-genomics::danrer10-reference-genome-ucsc-v1-1-1
running your command again with `-v` will provide additional information
location of failed script: /scratch/miniconda3/envs/segzoo_env/bin/.danrer10-reference-genome-ucsc-v1-post-link.sh
==> script messages <==
<None>

Attempting to roll back.

done
ERROR conda.core.link:_execute(637): An error occurred while installing package 'ggd-genomics::danrer10-reference-genome-ucsc-v1-1-1'.
LinkError: post-link script failed for package ggd-genomics::danrer10-reference-genome-ucsc-v1-1-1
running your command again with `-v` will provide additional information
location of failed script: /scratch/miniconda3/envs/segzoo_env/bin/.danrer10-reference-genome-ucsc-v1-post-link.sh
==> script messages <==
<None>

Attempting to roll back.

Rolling back transaction: done

CondaMultiError: LinkError: post-link script failed for package ggd-genomics::danrer10-reference-genome-ucsc-v1-1-1
running your command again with `-v` will provide additional information
location of failed script: /scratch/miniconda3/envs/segzoo_env/bin/.danrer10-reference-genome-ucsc-v1-post-link.sh
==> script messages <==
<None>

()

**Comment by mikecormier** [comment]
Hi @idaL, thanks for the report. From the output, I assume you are using `conda install danrer10-reference-genome-ucsc-v1 --prefix <target-prefix>`. This functionality no longer works due to a discrepancy in the post-link script for a recipe and conda's ability to source the target prefix. 

We are planning on a new cli update in the next few weeks, which should include a workaround for installing a data package from one environment to another. 

For now, you will need to run the `ggd install` command within the environment in which you want the data to be stored. 

Sorry for the inconvenience, and thank you for your patients.

**Comment by idaL** [comment]
Thank you so much @mikecormier !! Is it possible to also have this latest version of ggd up on pypi? It will make it possible to add ggd as a dependency in setup.py, allowing us to use the command ggd install

**Comment by mikecormier** [comment]
ggd will be added to pypi and conda in the near future.

**Comment by mikecormier** [comment]
Hey @idaL. GGD has been active on conda for almost a year now. Refer to the docs if you have any initial questions: https://gogetdata.github.io/. There should not be any post-link problems. 

I am closing this issue. Feel free to reach out if you have any other questions or concerns.
